---
cache:
  directories: ~
matrix:
  include:
    -
      addons:
        apt:
          packages:
            - lib32stdc++6
            - libstdc++6
            - fonts-droid
          sources:
            - ubuntu-toolchain-r-test
      before_install:
        - "openssl aes-256-cbc -K $encrypted_684cec268945_key -iv $encrypted_684cec268945_iv -in secrets.tar.enc -out secrets.tar -d"
        - "tar xvf secrets.tar"
      before_script:
        - ./scripts/before_build_apks.sh
        - "export ANDROID_HOME=$HOME/android-sdk"
        - "export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH"
      before_deploy:
        - git tag -f "travis-build"
      deploy:
        provider: releases
        api_key: $GITHUB_API_KEY
        file_glob: true
        file: build/app/outputs/apk/release/app-release.apk
        skip_cleanup: true
        overwrite: true
        prerelease: true
        target_commitsh: $TRAVIS_COMMIT
        on:
          branch: master
          repo: mbhanuprsd/MovieGo
      after_deploy:
        - rm -rf build/app/outputs
      env:
        - "SHARD=\"Build example apks\""
      jdk: oraclejdk8
      os: linux
      script:
        - "flutter build apk"
      sudo: false
#    -
#      before_install:
#        - "openssl aes-256-cbc -K $encrypted_684cec268945_key -iv $encrypted_684cec268945_iv -in secrets.tar.enc -out secrets.tar -d"
#        - "tar xvf secrets.tar"
#      before_script:
#        - ./scripts/before_build_ipas.sh
#        - "export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH"
#      env:
#        - "SHARD=\"Build example ipas\""
#      language: generic
#      os: osx
#      osx_image: xcode9.3
#      script:
#        - "flutter build ios --no-codesign"
