matrix:
  include:
  - os: linux
    env:
    - SHARD=Analyze
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
    - git clone https://github.com/flutter/flutter.git $HOME/flutter
    - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
    - flutter doctor
    script:
    - flutter analyze
  - os: linux
    env:
    - SHARD="Build example apks"
    jdk: oraclejdk8
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - lib32stdc++6
        - libstdc++6
        - fonts-droid
    before_install:
    - openssl aes-256-cbc -K $encrypted_684cec268945_key -iv $encrypted_684cec268945_iv -in
        google-services.json.enc -out android/app/google-services.json -d
    - openssl aes-256-cbc -K $encrypted_684cec268945_key -iv $encrypted_684cec268945_iv -in tmdb
    .dart.enc -out lib/tmdb.dart -d
    before_script:
    - "./scripts/before_build_apks.sh"
    - export ANDROID_HOME=$HOME/android-sdk
    - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
    script:
    - cd ./example
    - flutter build apk
  - os: osx
    env:
    - SHARD="Build example ipas"
    language: generic
    osx_image: xcode9.3
    before_install:
    - openssl aes-256-cbc -K $encrypted_684cec268945_key -iv $encrypted_684cec268945_iv -in
    GoogleService-Info.plist.enc -out ios/Runner/GoogleService-Info.plist -d
    - openssl aes-256-cbc -K $encrypted_684cec268945_key -iv $encrypted_684cec268945_iv -in tmdb
    .dart.enc -out lib/tmdb.dart -d
    before_script:
    - "./scripts/before_build_ipas.sh"
    - export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
    script:
    - cd ./example
    - flutter build ios --no-codesign
cache:
  directories: