---
branches:
  only:
    - master
cache:
  directories: ~
matrix:
  include:
    -
      addons:
        apt:
          packages:
            - lib32stdc++6
            - libstdc++6
            - fonts-droid
          sources:
            - ubuntu-toolchain-r-test
      before_install:
        - "openssl aes-256-cbc -K $encrypted_684cec268945_key -iv $encrypted_684cec268945_iv -in secrets.tar.enc -out secrets.tar -d"
        - "tar xvf secrets.tar"
      before_script:
        - ./scripts/before_build_apks.sh
        - "export ANDROID_HOME=$HOME/android-sdk"
        - "export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH"
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "Bhanu Prasad M"
        - git config --local user.email "mbhanuprsd@gmail.com"
        - export TRAVIS_TAG=Android-${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h
        -1)}
        - git tag $TRAVIS_TAG
      deploy:
        api_key:
          secure: cZjPkZ7B0/FNH8rSoVNMChyxoXWA0y1Ler5zNNwhqSf19shLh+JaPI/AEeJsq+zBpqcefcqcEujZ4m7KJblRHGwfgiB9VLVK9+ZMSc4jVTrXw5/s9hXkl2N+F0HRUM2wrnTXguem/VmYQpv/Z0Mf0poPXqt9MiNXPcZGWzcekc/Lun1HMk9MZIilsnExuODj5hnKiFqC+/V1bHzHwmi0P8ZGQ0cXIyhBHFP9LVnzuUKOhiZ2iTK8rhuOf7s7rIWpO/ZyCJq2Y6fCqzoszoDvhoE+BPL6fQCwpk24oUWM1K/HUS0EIg66BY88I8+Qcszr87GKzSEKUaHW5sUp1O2tGWk92HeX98LZ7Xj9P9opkKhKA5ovJYzbPwzum0DoHqVVNOhgahBJKFHlUZVzQjp4XLg3xRLLMLes3Y/r9m9UhClTW5UBZXQ/y7cEXs/zT0wJcztS/AVUOz5HtgWpumNDwN5hYFsLMYUyjWN8dJrTZFFiB0pL23eh8tB+Tjs3HHytOKnKiIxX0b/LQKDCba0v/HttgLkaGs+0ROvq3WEiLeMM+WpNEa5SormjxzG8mBvJ/sRDf5uRr2w86jCG6Y/ZiLijchwbrd/SE5EMW/hZJsWljWry0vNG0Q0081t+9ON/hmj9I2vDcbdRsHV6fw4DUZgk1TR9OgiomS2E8Ms5eKM=
        file: build/app/outputs/apk/release/app-release.apk
        provider: releases
        skip_cleanup: true
        on:
          repo: mbhanuprsd/MovieGo
          tags: fasle
      env:
        - "SHARD=\"Build example apks\""
      jdk: oraclejdk8
      os: linux
      script:
        - "flutter build apk"
      sudo: false
    -
      before_install:
        - "openssl aes-256-cbc -K $encrypted_684cec268945_key -iv $encrypted_684cec268945_iv -in secrets.tar.enc -out secrets.tar -d"
        - "tar xvf secrets.tar"
      before_script:
        - ./scripts/before_build_ipas.sh
        - "export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH"
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "Bhanu Prasad M"
        - git config --local user.email "mbhanuprsd@gmail.com"
        - export TRAVIS_TAG=iOS-${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
        - tar cvf Runner.tar /Users/travis/build/mbhanuprsd/MovieGo/build/ios/iphoneos/Runner.app
      deploy:
        api_key:
          secure: cZjPkZ7B0/FNH8rSoVNMChyxoXWA0y1Ler5zNNwhqSf19shLh+JaPI/AEeJsq+zBpqcefcqcEujZ4m7KJblRHGwfgiB9VLVK9+ZMSc4jVTrXw5/s9hXkl2N+F0HRUM2wrnTXguem/VmYQpv/Z0Mf0poPXqt9MiNXPcZGWzcekc/Lun1HMk9MZIilsnExuODj5hnKiFqC+/V1bHzHwmi0P8ZGQ0cXIyhBHFP9LVnzuUKOhiZ2iTK8rhuOf7s7rIWpO/ZyCJq2Y6fCqzoszoDvhoE+BPL6fQCwpk24oUWM1K/HUS0EIg66BY88I8+Qcszr87GKzSEKUaHW5sUp1O2tGWk92HeX98LZ7Xj9P9opkKhKA5ovJYzbPwzum0DoHqVVNOhgahBJKFHlUZVzQjp4XLg3xRLLMLes3Y/r9m9UhClTW5UBZXQ/y7cEXs/zT0wJcztS/AVUOz5HtgWpumNDwN5hYFsLMYUyjWN8dJrTZFFiB0pL23eh8tB+Tjs3HHytOKnKiIxX0b/LQKDCba0v/HttgLkaGs+0ROvq3WEiLeMM+WpNEa5SormjxzG8mBvJ/sRDf5uRr2w86jCG6Y/ZiLijchwbrd/SE5EMW/hZJsWljWry0vNG0Q0081t+9ON/hmj9I2vDcbdRsHV6fw4DUZgk1TR9OgiomS2E8Ms5eKM=
        file: Runner.tar
        provider: releases
        skip_cleanup: true
        on:
          repo: mbhanuprsd/MovieGo
          tags: fasle
          branches:
            only:
              - master
      env:
        - "SHARD=\"Build example ipas\""
      language: generic
      os: osx
      osx_image: xcode9.3
      script:
        - "travis_wait flutter build ios --no-codesign"
